conference-rooms:
  rooms:
    - name: "Amaze"
      capacity: 3
      maintenance-schedule:
        - start: "09:00"
          end: "09:15"
        - start: "13:00"
          end: "13:15"
        - start: "17:00"
          end: "17:15"
    - name: "Beauty"
      capacity: 7
      maintenance-schedule:
        - start: "09:00"
          end: "09:15"
        - start: "13:00"
          end: "13:15"
        - start: "17:00"
          end: "17:15"
    - name: "Inspire"
      capacity: 12
      maintenance-schedule:
        - start: "09:00"
          end: "09:15"
        - start: "13:00"
          end: "13:15"
        - start: "17:00"
          end: "17:15"
    - name: "Strive"
      capacity: 20
      maintenance-schedule:
        - start: "09:00"
          end: "09:15"
        - start: "13:00"
          end: "13:15"
        - start: "17:00"
          end: "17:15"
